### ISSUE TITLE
Signal transmission

### ISSUE THREAD

**Issue by FayeWong98** [globsky/SignalSim#3]
Many thanks to the author for such an excellent program!

I have some confusion at the moment:

Can the signals generated by this project be transmitted out with a device such as an SDR for GNSS receiver spoofing tests?

Also, is it possible to use raw binary navigation messages as input and thus perform signal forgery?

Have a nice life!

**Comment by globsky** [comment]
The navigation message is generated by class NaBit derived classes for different message type. 
Class CSatelliteSignal will use above classes to generate modulated signal at given epoch.
Realtime signal generation using SDR is also achievable by above method (it is actually a GNSS signal simulator). By doing this, you need to implement following components by yourself: hardware logic to interpolate carrier residual for each IF sample; PRN code generation and interpolation for each IF sample; noise model to generate noise. Then you will get digital IF signal. You can use SDR to do DAC and up-converting to generate RF signal.
