### ISSUE TITLE
多频输出

### ISSUE THREAD

**Issue by heiwa0519** [globsky/SignalSim#4]
您好，SignalSim是否暂时只支持单频观测数据输出？

**Comment by globsky** [comment]
可以支持多频，GetTravelTime()，GetCarrierPhase()，GetDoppler()这几个用于计算观测量的函数，以及获得调制信号的CSatelliteSignal类在开始时需要设置的信号属性的SetSignalAttribute()函数都有一个FreqIndex参数，可以在SatelliteParam.h中找到定义。目前可以包含不同频点的电离层延时差。卫星上的ISC（inter-signal correction）需要等待以后对RINEX4格式支持的完善。
