### ISSUE TITLE
Fail to simulate double frequency observations

### ISSUE THREAD

**Issue by WangJitaoNAV** [globsky/SignalSim#5]
Thanks for your excellent work!
I met one problem and need help. I could not simulate double frequency observations successfully by simply using the modified configuration file. Here are my configurations of output part:
```xml
<Output type="observation" format="RINEX">
        <Interval unit="s">1</Interval>
        <Name>test2.o</Name>
        <ConfigParam>
            <ElevationMask>3</ElevationMask>
        </ConfigParam>
        <SystemSelect system="GPS" freq="L1" freq="L2">true</SystemSelect>
        <SystemSelect system="BDS" freq="B1C" freq="B3I">true</SystemSelect>
        <SystemSelect system="Galileo">true</SystemSelect>
</Output>
```
And the other configurations are the same as you provide. I have checked that the ephemeris file path is correct. Could you tell me the possible reason for my failure to simulate double frequency observations? Thanks!

**Comment by globsky** [comment]
New committed version add multi-frequency observation in the structure to solve this issue.
Currently only support maximum 3 frequencies for each system (due to single line SYS/OBS header for each system)
The scenario should use one separate line for each frequency instead of each system as shown below:
        <SystemSelect system="GPS" freq="L1">true</SystemSelect>
        <SystemSelect system="GPS" freq="L2">true</SystemSelect>
        <SystemSelect system="BDS">true</SystemSelect>
        <SystemSelect system="BDS" freq="B3I">true</SystemSelect>
